#!/bin/bash
# post-compact hook — runs after context compaction
# Generated by audit v2 (2026-05-03)

echo "[post-compact] Restoring checkpoint state..."

# Restore hot memory from backup
cp /tmp/legion_session_context.backup /tmp/legion_session_context.txt 2>/dev/null || true
cp /tmp/legion_hermes_skills.backup /tmp/legion_hermes_skills.txt 2>/dev/null || true

# Clean backup files
rm -f /tmp/legion_session_context.backup /tmp/legion_hermes_skills.backup

echo "[post-compact] Restoration complete"
