#!/bin/bash
# post-compact.sh — runs after context compaction completes
# Generated by audit (2026-05-04)

echo "[post-compact] Restoring session state..."

# Restore hot memory from backup
cp /tmp/legion_session_context.backup /tmp/legion_session_context.txt 2>/dev/null || true
cp /tmp/legion_hermes_skills.backup /tmp/legion_hermes_skills.txt 2>/dev/null || true

# Load last user prompt back into session context
# This ensures the verbatim last prompt is available for next session start
if [ -f /tmp/legion_last_user_prompt.txt ]; then
    content=$(cat /tmp/legion_last_user_prompt.txt)
    if [ "$content" != "NO_USER_PROMPT" ] && [ ${#content} -gt 5 ]; then
        echo "[post-compact] Last prompt restored (${#content} chars)"
    fi
fi

echo "[post-compact] Session state restored from checkpoint"
