#!/bin/bash
# post-session.sh — runs after each OpenCode session ends
# Generated by audit (2026-05-04)

echo "[post-session] Saving session state..."

# Export session memory to hot tier
if [ -f /tmp/legion_session_context.txt ]; then
    cp /tmp/legion_session_context.txt "${HOME}/.legion/sessions/latest" 2>/dev/null || true
fi

# Write session summary to daily log
SESSION_LOG="${HOME}/.legion/logs/sessions/$(date +%Y-%m-%d).md"
mkdir -p "$(dirname "$SESSION_LOG")"
echo "## $(date +%H:%M) — Session ended" >> "$SESSION_LOG" 2>/dev/null || true

# Consolidate hermes skills
python3 -c "
import sys
sys.path.insert(0, '.')
try:
    from tools.mem0_client import get_mem0, mem0_add
    import datetime
    m = get_mem0()
    # Session summary stored by memory_consolidate worker
except Exception:
    pass
" 2>/dev/null || true

echo "[post-session] Session saved"
