#!/bin/bash
# pre-compact hook — runs before context compaction
# Generated by audit v2 (2026-05-03)

echo "[pre-compact] Saving checkpoint state..."

# Write sticky context (files actively in use)
python3 .claude/scripts/wiki_health.py 2>/dev/null || true

# Save hot memory files
cp /tmp/legion_session_context.txt /tmp/legion_session_context.backup 2>/dev/null || true
cp /tmp/legion_hermes_skills.txt /tmp/legion_hermes_skills.backup 2>/dev/null || true

echo "[pre-compact] Checkpoint complete"
