"""handlers/e2e.py — End-to-end testing and Supabase query commands.

Commands:
  /e2etest <url>   — AI-guided Playwright E2E test runner (generates + runs + reports)
  /e2eplan <url>   — Generate a test plan without running (dry-run)
  /dbquery <query> — Natural-language Supabase query via LLM
  /dbhealth        — Check Supabase project connectivity + latency
  /dbtables        — List all public tables in the Supabase project
"""
from __future__ import annotations

import asyncio
import html as html_mod
import json
import os
import re
import textwrap
from pathlib import Path
from typing import Optional

from aiogram import Router
from aiogram.filters import Command
from aiogram.types import Message

from handlers.shared import is_allowed, send_chunked

router = Router()

_E2E_WORK_DIR = Path("/tmp/legion_e2e")


# =========================================================================== #
# Helpers (defined at top so all functions can use them)
# =========================================================================== #

def _extract_code_block(text: str) -> str:
    """Extract content from first ```...``` block."""
    m = re.search(r"```(?:typescript|ts|javascript|js|python)?\n([\s\S]*?)```", text)
    if m:
        return m.group(1).strip()
    return ""


async def _run_shell(cmd: str, timeout: int = 60) -> str:
    """Run a shell command asynchronously, return stdout+stderr combined."""
    try:
        proc = await asyncio.wait_for(
            asyncio.create_subprocess_shell(
                cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.STDOUT,
            ),
            timeout=5,  # process creation timeout
        )
        stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=timeout)
        return (stdout or b"").decode(errors="replace")
    except asyncio.TimeoutError:
        return f"[TIMEOUT after {timeout}s]"
    except Exception as e:
        return f"[shell error: {e}]"


# =========================================================================== #
# /e2etest
# =========================================================================== #

@router.message(Command("e2etest"))
async def cmd_e2etest(msg: Message) -> None:
    """AI-guided Playwright E2E test against a URL."""
    if not is_allowed(msg):
        return

    url = (msg.text or "").removeprefix("/e2etest").strip()
    if not url:
        await msg.answer(
            "Usage: <code>/e2etest https://your-site.com</code>\n"
            "I'll generate and run Playwright tests against that URL.",
            parse_mode="HTML",
        )
        return

    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    status_msg = await msg.answer(
        f"\U0001f9ea Starting E2E test for <code>{html_mod.escape(url)}</code>\u2026\n"
        "Step 1/4: Generating test plan…",
        parse_mode="HTML",
    )

    user_id = str(msg.from_user.id) if msg.from_user else "0"

    try:
        from llm_client import chat

        # Step 1: Generate test code
        plan_prompt = textwrap.dedent(f"""\
            You are a senior QA engineer. Analyse the website at: {url}

            Generate a Playwright E2E test plan. Include:
            1. List of 3-5 critical user journeys to test
            2. Key pages and interactions to verify
            3. Things to check: auth, forms, navigation, responsive layout, API calls

            Then write a complete working Playwright test file (TypeScript) that:
            - Tests all the journeys you listed
            - Uses data-testid selectors where possible, fallback to ARIA roles
            - Includes proper async/await and expect assertions
            - Saves screenshots on failure
            - Can run headlessly with: npx playwright test

            Output ONLY the TypeScript test file content inside a ```typescript code block.
            No explanation before or after the code block.
        """)

        plan_response, plan_model = await chat(
            plan_prompt,
            agent_key="reviewer",
            user_id=user_id,
        )

        test_code = _extract_code_block(plan_response) or plan_response

        await status_msg.edit_text(
            f"\U0001f9ea E2E test for <code>{html_mod.escape(url)}</code>\n"
            f"Step 2/4: Writing test file\u2026 (via {html_mod.escape(plan_model)})",
            parse_mode="HTML",
        )

        # Step 2: Write test file
        _E2E_WORK_DIR.mkdir(parents=True, exist_ok=True)
        test_file = _E2E_WORK_DIR / "generated.spec.ts"
        config_file = _E2E_WORK_DIR / "playwright.config.ts"

        test_file.write_text(
            f"// Generated by Legion for: {url}\n"
            f"// Model: {plan_model}\n\n"
            + test_code,
            encoding="utf-8",
        )

        config_file.write_text(
            textwrap.dedent(f"""\
                import {{ defineConfig }} from '@playwright/test';
                export default defineConfig({{
                  testDir: '.',
                  use: {{
                    baseURL: '{url}',
                    headless: true,
                    screenshot: 'only-on-failure',
                    video: 'off',
                  }},
                  reporter: [['json', {{ outputFile: '/tmp/legion_e2e/results.json' }}], ['line']],
                }});
            """),
            encoding="utf-8",
        )

        await status_msg.edit_text(
            f"\U0001f9ea E2E test for <code>{html_mod.escape(url)}</code>\n"
            "Step 3/4: Installing Playwright + running tests\u2026",
            parse_mode="HTML",
        )

        # Step 3: Check/install Playwright, then run
        check_out = await _run_shell("which npx 2>&1 && npx playwright --version 2>&1", timeout=10)
        if "not found" in check_out.lower() or "error" in check_out.lower():
            install_out = await _run_shell(
                "npm install -g @playwright/test 2>&1 | tail -5",
                timeout=120,
            )
            await status_msg.edit_text(
                f"\U0001f9ea Installing Playwright:\n"
                f"<pre>{html_mod.escape(install_out[:300])}</pre>\n"
                "Running tests\u2026",
                parse_mode="HTML",
            )
            await _run_shell(
                "npx playwright install --with-deps chromium 2>&1 | tail -5",
                timeout=180,
            )

        run_out = await _run_shell(
            f"cd {_E2E_WORK_DIR} && npx playwright test generated.spec.ts "
            f"--config playwright.config.ts 2>&1 | tail -40",
            timeout=120,
        )

        # Step 4: Summarise results
        await status_msg.edit_text(
            f"\U0001f9ea E2E test for <code>{html_mod.escape(url)}</code>\n"
            "Step 4/4: Analysing results\u2026",
            parse_mode="HTML",
        )

        summary_prompt = textwrap.dedent(f"""\
            Playwright test run output:
            ```
            {run_out[:3000]}
            ```

            Summarise in this format:
            ## E2E Report — {url}
            ✅ PASSED: N
            ❌ FAILED: N
            ⏭ SKIPPED: N

            ### Failed Tests
            (list each failure with error)

            ### Verdict
            (PASS / FAIL / PARTIAL + one-line recommendation)
        """)

        summary, _ = await chat(summary_prompt, agent_key="analyst", user_id=user_id)

        code_snippet = test_code[:1500] + ("\n\u2026(truncated)" if len(test_code) > 1500 else "")
        final = (
            f"<b>\U0001f9ea E2E Test Complete — {html_mod.escape(url)}</b>\n\n"
            f"{html_mod.escape(summary)}\n\n"
            f"<b>Generated Test File:</b>\n"
            f"<pre>{html_mod.escape(code_snippet)}</pre>"
        )

        try:
            await status_msg.delete()
        except Exception:
            pass

        await send_chunked(msg, final)

    except Exception as e:
        try:
            await status_msg.edit_text(
                f"\u274c E2E test failed: <code>{html_mod.escape(str(e)[:300])}</code>",
                parse_mode="HTML",
            )
        except Exception:
            await msg.answer(
                f"\u274c E2E test failed: <code>{html_mod.escape(str(e)[:300])}</code>",
                parse_mode="HTML",
            )


# =========================================================================== #
# /e2eplan
# =========================================================================== #

@router.message(Command("e2eplan"))
async def cmd_e2eplan(msg: Message) -> None:
    """Generate E2E test plan without running (dry-run)."""
    if not is_allowed(msg):
        return

    url = (msg.text or "").removeprefix("/e2eplan").strip()
    if not url:
        await msg.answer(
            "Usage: <code>/e2eplan https://your-site.com</code>\n"
            "Generates a test plan + skeleton test file (no execution).",
            parse_mode="HTML",
        )
        return
    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    user_id = str(msg.from_user.id) if msg.from_user else "0"
    wait = await msg.answer("\U0001f4cb Generating test plan\u2026", parse_mode="HTML")
    try:
        from llm_client import chat
        prompt = (
            f"Generate a detailed Playwright E2E test plan for: {url}\n\n"
            "Include: user journeys, test scenarios, selector strategy, "
            "data requirements, and a skeleton test file. "
            "Format with clear markdown headers."
        )
        result, model = await chat(prompt, agent_key="reviewer", user_id=user_id)
        try:
            await wait.delete()
        except Exception:
            pass
        await send_chunked(
            msg,
            f"<b>\U0001f4cb E2E Plan — {html_mod.escape(url)}</b>\n\n{html_mod.escape(result)}",
        )
    except Exception as e:
        try:
            await wait.edit_text(
                f"\u274c {html_mod.escape(str(e)[:200])}",
                parse_mode="HTML",
            )
        except Exception:
            pass


# =========================================================================== #
# /dbquery
# =========================================================================== #

@router.message(Command("dbquery"))
async def cmd_dbquery(msg: Message) -> None:
    """Natural-language or raw PostgREST query against Supabase."""
    if not is_allowed(msg):
        return

    query_text = (msg.text or "").removeprefix("/dbquery").strip()
    if not query_text:
        await msg.answer(
            "Usage: <code>/dbquery &lt;natural language or table query&gt;</code>\n\n"
            "Examples:\n"
            "  <code>/dbquery show last 10 bookings</code>\n"
            "  <code>/dbquery count users created this week</code>\n"
            "  <code>/dbquery table=bookings select=id,status eq=status.pending</code>",
            parse_mode="HTML",
        )
        return

    from tools.supabase_client import is_configured
    if not is_configured():
        await msg.answer(
            "\u26a0\ufe0f Supabase is not configured.\n"
            "Add these to your <code>.env</code>:\n"
            "<pre>SUPABASE_URL=https://&lt;project&gt;.supabase.co\n"
            "SUPABASE_ANON_KEY=&lt;your-anon-key&gt;\n"
            "SUPABASE_SERVICE_ROLE_KEY=&lt;your-service-role-key&gt;</pre>",
            parse_mode="HTML",
        )
        return

    wait = await msg.answer("\U0001f5c4 Querying Supabase\u2026", parse_mode="HTML")

    if query_text.startswith("table="):
        result = await _raw_db_query(query_text)
    else:
        user_id = str(msg.from_user.id) if msg.from_user else "0"
        result = await _nl_db_query(query_text, user_id)

    try:
        await wait.delete()
    except Exception:
        pass
    await send_chunked(msg, result)


async def _raw_db_query(query_text: str) -> str:
    """Parse table=X select=Y eq=K.V format and query Supabase directly."""
    try:
        from tools.supabase_client import get_client
        db = get_client()

        parts = dict(p.split("=", 1) for p in query_text.split() if "=" in p)
        table = parts.get("table", "")
        if not table:
            return "\u274c Missing <code>table=</code> parameter."

        select = parts.get("select", "*")
        limit = int(parts.get("limit", "20"))
        eq: dict = {}
        if "eq" in parts:
            for kv in parts["eq"].split(","):
                if "." in kv:
                    k, v = kv.split(".", 1)
                    eq[k] = v

        rows = await db.query(table, select=select, eq=eq, limit=limit)
        if not rows:
            return f"\U0001f5c4 No rows found in <code>{html_mod.escape(table)}</code>."

        header = f"<b>\U0001f5c4 {html_mod.escape(table)}</b> — {len(rows)} rows\n\n"
        preview = json.dumps(rows[:10], indent=2, ensure_ascii=False, default=str)
        return header + "<pre>" + html_mod.escape(preview[:3000]) + "</pre>"

    except Exception as e:
        return f"\u274c DB query error: <code>{html_mod.escape(str(e)[:300])}</code>"


async def _nl_db_query(query_text: str, user_id: str = "0") -> str:
    """Use LLM to translate natural language to a Supabase query, then execute."""
    try:
        from llm_client import chat
        from tools.supabase_client import get_client

        prompt = textwrap.dedent(f"""\
            Convert this natural language database request into a JSON Supabase query spec:
            Request: "{query_text}"

            Output ONLY valid JSON in this exact format (no markdown fences, no explanation):
            {{"table": "table_name", "select": "col1,col2", "eq": {{}}, "order": "created_at.desc", "limit": 20}}

            Rules:
            - Use common Supabase table names (users, bookings, orders, profiles, etc.)
            - select="*" if unsure which columns
            - eq={{}} if no filter needed
            - order="created_at.desc" for "latest/recent"
            - limit=10 for "few", limit=100 for "all"
            - Output ONLY the JSON object on a single line. No code blocks.
        """)

        spec_str, _ = await chat(prompt, agent_key="analyst", user_id=user_id)

        # Strip any markdown fences the model adds despite instructions
        spec_str = re.sub(r"^```[a-z]*\n?", "", spec_str.strip())
        spec_str = re.sub(r"```$", "", spec_str.strip()).strip()

        # Extract first JSON object if surrounded by prose
        json_match = re.search(r"\{[\s\S]+\}", spec_str)
        if json_match:
            spec_str = json_match.group(0)

        try:
            spec = json.loads(spec_str)
        except json.JSONDecodeError as je:
            return (
                f"\u26a0\ufe0f Could not parse query spec (JSONDecodeError: {je})\n"
                f"<pre>{html_mod.escape(spec_str[:400])}</pre>\n"
                "Try: <code>/dbquery table=&lt;name&gt; select=* limit=10</code>"
            )

        db = get_client()
        rows = await db.query(
            table=spec.get("table", ""),
            select=spec.get("select", "*"),
            eq=spec.get("eq", {}),
            order=spec.get("order"),
            limit=int(spec.get("limit", 20)),
        )

        if not rows:
            return f"\U0001f5c4 No results for: <i>{html_mod.escape(query_text)}</i>"

        table_name = spec.get("table", "?")
        header = f"<b>\U0001f5c4 {html_mod.escape(table_name)}</b> — {len(rows)} rows\n"
        header += f"<i>Query: {html_mod.escape(query_text)}</i>\n\n"
        preview = json.dumps(rows[:10], indent=2, ensure_ascii=False, default=str)
        return header + "<pre>" + html_mod.escape(preview[:3000]) + "</pre>"

    except Exception as e:
        return f"\u274c DB query error: <code>{html_mod.escape(str(e)[:300])}</code>"


# =========================================================================== #
# /dbhealth
# =========================================================================== #

@router.message(Command("dbhealth"))
async def cmd_dbhealth(msg: Message) -> None:
    """Check Supabase project health and latency."""
    if not is_allowed(msg):
        return

    from tools.supabase_client import is_configured
    if not is_configured():
        await msg.answer(
            "\u26a0\ufe0f Supabase not configured. Set SUPABASE_URL + SUPABASE_ANON_KEY in .env",
            parse_mode="HTML",
        )
        return

    try:
        from tools.supabase_client import get_client
        db = get_client()
        health = await db.health_check()
        url_str = os.getenv("SUPABASE_URL", "?")
        svc_set = bool(os.getenv("SUPABASE_SERVICE_ROLE_KEY"))

        if health["ok"]:
            icon = "\u2705"
            status_str = f"Online ({health['latency_ms']}ms)"
        else:
            icon = "\u274c"
            status_str = health.get("error") or f"HTTP {health.get('status_code')}"

        await msg.answer(
            f"{icon} <b>Supabase Health</b>\n"
            f"URL: <code>{html_mod.escape(url_str)}</code>\n"
            f"Status: <b>{html_mod.escape(str(status_str))}</b>\n"
            f"Service Role Key: {'\u2705 set' if svc_set else '\u26a0\ufe0f not set (RLS bypass disabled)'}",
            parse_mode="HTML",
        )
    except Exception as e:
        await msg.answer(
            f"\u274c Health check failed: <code>{html_mod.escape(str(e)[:200])}</code>",
            parse_mode="HTML",
        )


# =========================================================================== #
# /dbtables
# =========================================================================== #

@router.message(Command("dbtables"))
async def cmd_dbtables(msg: Message) -> None:
    """List public tables in the Supabase project via pg_catalog."""
    if not is_allowed(msg):
        return

    from tools.supabase_client import is_configured
    if not is_configured():
        await msg.answer("\u26a0\ufe0f Supabase not configured.", parse_mode="HTML")
        return

    try:
        from tools.supabase_client import get_client
        db = get_client()

        # Use RPC to query pg_tables — information_schema.tables is not a PostgREST endpoint
        try:
            rows = await db.rpc("list_public_tables", {})
        except Exception:
            # Fallback: query pg_catalog.pg_tables via direct PostgREST
            # This works if service role is set (bypasses RLS on system tables)
            try:
                rows = await db.query(
                    "pg_catalog.pg_tables",
                    select="tablename",
                    eq={"schemaname": "public"},
                    order="tablename.asc",
                    limit=100,
                )
                rows = [{"table_name": r["tablename"], "table_type": "BASE TABLE"} for r in rows]
            except Exception:
                rows = []

        if not rows:
            await msg.answer(
                "\U0001f5c4 No public tables found, or the <code>list_public_tables</code> "
                "RPC function is not installed.\n\n"
                "<b>To enable /dbtables, run in Supabase SQL editor:</b>\n"
                "<pre>CREATE OR REPLACE FUNCTION list_public_tables()\n"
                "RETURNS TABLE(table_name text, table_type text)\n"
                "LANGUAGE sql SECURITY DEFINER AS $$\n"
                "  SELECT table_name::text, table_type::text\n"
                "  FROM information_schema.tables\n"
                "  WHERE table_schema = 'public'\n"
                "  ORDER BY table_name;\n"
                "$$;</pre>",
                parse_mode="HTML",
            )
            return

        lines = ["<b>\U0001f5c4 Supabase Tables (public schema)</b>\n"]
        for r in rows:
            t = r.get("table_name", "?")
            tt = r.get("table_type", "BASE TABLE")
            icon = "\U0001f4c4" if tt == "BASE TABLE" else "\U0001f441"
            lines.append(f"  {icon} <code>{html_mod.escape(str(t))}</code>")

        await msg.answer("\n".join(lines), parse_mode="HTML")

    except Exception as e:
        await msg.answer(
            f"\u274c Could not list tables: <code>{html_mod.escape(str(e)[:200])}</code>",
            parse_mode="HTML",
        )
