"""handlers/e2e.py — End-to-end testing and Supabase query commands.

Commands:
  /e2etest <url>        — AI-guided Playwright E2E test run against a URL
  /e2eplan <url>        — Generate a test plan without running (dry-run)
  /dbquery <query>      — Natural-language or raw SQL query against Supabase
  /dbhealth             — Check Supabase project connectivity + latency
  /dbtables             — List all public tables in the Supabase project
"""
from __future__ import annotations

import html as html_mod
import json
import os
import textwrap
from pathlib import Path

from aiogram import Router
from aiogram.filters import Command
from aiogram.types import Message

from handlers.shared import is_allowed, send_chunked

router = Router()

_E2E_WORK_DIR = Path("/tmp/legion_e2e")


# =========================================================================== #
# /e2etest
# =========================================================================== #

@router.message(Command("e2etest"))
async def cmd_e2etest(msg: Message) -> None:
    """AI-guided Playwright E2E test against a URL."""
    if not is_allowed(msg):
        return

    url = (msg.text or "").removeprefix("/e2etest").strip()
    if not url:
        await msg.answer(
            "Usage: <code>/e2etest https://your-site.com</code>\n"
            "I'll generate and run Playwright tests against that URL.",
            parse_mode="HTML",
        )
        return

    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    status_msg = await msg.answer(
        f"\U0001f9ea Starting E2E test for <code>{html_mod.escape(url)}</code>\u2026\n"
        "Step 1/4: Generating test plan…",
        parse_mode="HTML",
    )

    try:
        from llm_client import chat

        # Step 1: Generate test plan
        plan_prompt = textwrap.dedent(f"""\
            You are a senior QA engineer. Analyse the website at: {url}

            Generate a Playwright E2E test plan. Include:
            1. List of 3-5 critical user journeys to test
            2. Key pages and interactions to verify
            3. Things to check: auth, forms, navigation, responsive layout, API calls

            Then write a complete working Playwright test file (TypeScript) that:
            - Tests all the journeys you listed
            - Uses data-testid selectors where possible, fallback to ARIA roles
            - Includes proper async/await and expect assertions
            - Saves screenshots on failure
            - Can run headlessly with: npx playwright test

            Output ONLY the TypeScript test file content inside a ```typescript code block.
            No explanation before or after the code block.
        """)

        plan_response, plan_model = await chat(plan_prompt, agent_key="reviewer")

        # Extract code block
        test_code = _extract_code_block(plan_response)
        if not test_code:
            test_code = plan_response  # fallback: use raw response

        await status_msg.edit_text(
            f"\U0001f9ea E2E test for <code>{html_mod.escape(url)}</code>\n"
            f"Step 2/4: Writing test file\u2026 (via {html_mod.escape(plan_model)})",
            parse_mode="HTML",
        )

        # Step 2: Write test file
        _E2E_WORK_DIR.mkdir(parents=True, exist_ok=True)
        test_file = _E2E_WORK_DIR / "generated.spec.ts"
        config_file = _E2E_WORK_DIR / "playwright.config.ts"

        test_file.write_text(
            f"// Generated by Legion for: {url}\n"
            f"// Model: {plan_model}\n\n"
            + test_code,
            encoding="utf-8",
        )

        config_file.write_text(
            textwrap.dedent(f"""\
                import {{ defineConfig }} from '@playwright/test';
                export default defineConfig({{
                  testDir: '.',
                  use: {{
                    baseURL: '{url}',
                    headless: true,
                    screenshot: 'only-on-failure',
                    video: 'off',
                  }},
                  reporter: [['json', {{ outputFile: '/tmp/legion_e2e/results.json' }}], ['line']],
                }});
            """),
            encoding="utf-8",
        )

        await status_msg.edit_text(
            f"\U0001f9ea E2E test for <code>{html_mod.escape(url)}</code>\n"
            "Step 3/4: Installing Playwright + running tests\u2026",
            parse_mode="HTML",
        )

        # Step 3: Run tests via computer_agent shell
        try:
            from llm_client import run_shell_command
            # Check/install playwright
            check = await run_shell_command(
                "which npx && npx playwright --version 2>&1 || echo 'NOT_INSTALLED'"
            )
            if "NOT_INSTALLED" in check or "not found" in check:
                install_out = await run_shell_command(
                    "npm install -g playwright @playwright/test 2>&1 | tail -5"
                )
                await status_msg.edit_text(
                    f"\U0001f9ea E2E test — installed Playwright:\n<pre>{html_mod.escape(install_out[:400])}</pre>\n"
                    "Running tests\u2026",
                    parse_mode="HTML",
                )
                await run_shell_command(
                    "npx playwright install --with-deps chromium 2>&1 | tail -3"
                )

            run_out = await run_shell_command(
                f"cd {_E2E_WORK_DIR} && npx playwright test generated.spec.ts "
                f"--config playwright.config.ts 2>&1 | tail -40",
                timeout=120,
            )

        except Exception as shell_err:
            run_out = f"Shell execution failed: {shell_err}\n(Is computer_agent available?)"

        # Step 4: Parse results and summarise
        await status_msg.edit_text(
            f"\U0001f9ea E2E test for <code>{html_mod.escape(url)}</code>\n"
            "Step 4/4: Analysing results\u2026",
            parse_mode="HTML",
        )

        summary_prompt = textwrap.dedent(f"""\
            Playwright test run output:
            ```
            {run_out[:3000]}
            ```

            Summarise in this format:
            ## E2E Report — {url}
            ✅ PASSED: N
            ❌ FAILED: N
            ⏭ SKIPPED: N

            ### Failed Tests
            (list each failure with error)

            ### Verdict
            (PASS / FAIL / PARTIAL + one-line recommendation)
        """)

        summary, _ = await chat(summary_prompt, agent_key="analyst")

        # Send test code + summary
        code_snippet = test_code[:1500] + ("\n...(truncated)" if len(test_code) > 1500 else "")
        final = (
            f"<b>\U0001f9ea E2E Test Complete — {html_mod.escape(url)}</b>\n\n"
            f"{html_mod.escape(summary)}\n\n"
            f"<b>Generated Test File:</b>\n"
            f"<pre>{html_mod.escape(code_snippet)}</pre>"
        )
        await status_msg.delete()
        await send_chunked(msg, final)

    except Exception as e:
        await status_msg.edit_text(
            f"\u274c E2E test failed: <code>{html_mod.escape(str(e)[:300])}</code>",
            parse_mode="HTML",
        )


@router.message(Command("e2eplan"))
async def cmd_e2eplan(msg: Message) -> None:
    """Generate E2E test plan without running (dry-run)."""
    if not is_allowed(msg):
        return

    url = (msg.text or "").removeprefix("/e2eplan").strip()
    if not url:
        await msg.answer(
            "Usage: <code>/e2eplan https://your-site.com</code>\n"
            "Generates a test plan + skeleton test file (no execution).",
            parse_mode="HTML",
        )
        return
    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    wait = await msg.answer("\U0001f4cb Generating test plan\u2026", parse_mode="HTML")
    try:
        from llm_client import chat
        prompt = (
            f"Generate a detailed Playwright E2E test plan for: {url}\n\n"
            "Include: user journeys, test scenarios, selector strategy, "
            "data requirements, and a skeleton test file. "
            "Format with clear markdown headers."
        )
        result, model = await chat(prompt, agent_key="reviewer")
        await wait.delete()
        await send_chunked(msg, f"<b>\U0001f4cb E2E Plan — {html_mod.escape(url)}</b>\n\n{html_mod.escape(result)}")
    except Exception as e:
        await wait.edit_text(f"\u274c {html_mod.escape(str(e)[:200])}")


# =========================================================================== #
# /dbquery
# =========================================================================== #

@router.message(Command("dbquery"))
async def cmd_dbquery(msg: Message) -> None:
    """Natural-language or raw PostgREST query against Supabase."""
    if not is_allowed(msg):
        return

    query_text = (msg.text or "").removeprefix("/dbquery").strip()
    if not query_text:
        await msg.answer(
            "Usage: <code>/dbquery &lt;natural language or table query&gt;</code>\n\n"
            "Examples:\n"
            "  <code>/dbquery show last 10 bookings</code>\n"
            "  <code>/dbquery count users created this week</code>\n"
            "  <code>/dbquery table=bookings select=id,status eq=status.pending</code>",
            parse_mode="HTML",
        )
        return

    try:
        from tools.supabase_client import get_client, is_configured
        if not is_configured():
            await msg.answer(
                "\u26a0\ufe0f Supabase is not configured.\n"
                "Add these to your <code>.env</code>:\n"
                "<pre>SUPABASE_URL=https://&lt;project&gt;.supabase.co\n"
                "SUPABASE_ANON_KEY=&lt;your-anon-key&gt;\n"
                "SUPABASE_SERVICE_ROLE_KEY=&lt;your-service-role-key&gt;</pre>",
                parse_mode="HTML",
            )
            return
    except Exception:
        pass

    wait = await msg.answer("\U0001f5c4 Querying Supabase\u2026", parse_mode="HTML")

    # Check if it's a raw structured query: table=X select=Y eq=Z
    if query_text.startswith("table="):
        result = await _raw_db_query(query_text)
    else:
        result = await _nl_db_query(query_text)

    await wait.delete()
    await send_chunked(msg, result)


async def _raw_db_query(query_text: str) -> str:
    """Parse table=X select=Y eq=K.V format and query Supabase directly."""
    try:
        from tools.supabase_client import get_client
        db = get_client()

        parts = dict(p.split("=", 1) for p in query_text.split() if "=" in p)
        table = parts.get("table", "")
        if not table:
            return "\u274c Missing table= parameter."

        select = parts.get("select", "*")
        limit = int(parts.get("limit", "20"))
        eq: dict = {}
        if "eq" in parts:
            for kv in parts["eq"].split(","):
                if "." in kv:
                    k, v = kv.split(".", 1)
                    eq[k] = v

        rows = await db.query(table, select=select, eq=eq, limit=limit)
        if not rows:
            return f"\U0001f5c4 No rows found in <code>{html_mod.escape(table)}</code>."

        header = f"<b>\U0001f5c4 {html_mod.escape(table)}</b> — {len(rows)} rows\n\n"
        preview = json.dumps(rows[:10], indent=2, ensure_ascii=False, default=str)
        return header + "<pre>" + html_mod.escape(preview[:3000]) + "</pre>"

    except Exception as e:
        return f"\u274c DB query error: <code>{html_mod.escape(str(e)[:300])}</code>"


async def _nl_db_query(query_text: str) -> str:
    """Use LLM to translate natural language to a Supabase query, then execute."""
    try:
        from llm_client import chat
        from tools.supabase_client import get_client

        # Ask LLM to produce a structured query spec
        prompt = textwrap.dedent(f"""\
            Convert this natural language database request into a JSON Supabase query spec:
            Request: "{query_text}"

            Output ONLY valid JSON in this exact format:
            {{
              "table": "table_name",
              "select": "col1,col2,col3",
              "eq": {{"col": "value"}},
              "order": "created_at.desc",
              "limit": 20
            }}

            Rules:
            - Use common Supabase table names (users, bookings, orders, profiles, etc.)
            - select="*" if unsure which columns
            - eq={{}} if no filter needed
            - order="created_at.desc" for "latest/recent"
            - limit=10 for "few", limit=100 for "all"
            - Output ONLY the JSON object, no explanation.
        """)

        spec_str, _ = await chat(prompt, agent_key="analyst")
        spec_str = _extract_code_block(spec_str) or spec_str.strip()

        # Strip markdown json fences if present
        spec_str = spec_str.strip().lstrip("```json").lstrip("```").rstrip("```").strip()

        try:
            spec = json.loads(spec_str)
        except json.JSONDecodeError:
            return (
                f"\u26a0\ufe0f Could not parse query spec from LLM response.\n"
                f"<pre>{html_mod.escape(spec_str[:500])}</pre>\n"
                "Try: <code>/dbquery table=&lt;name&gt; select=* limit=10</code>"
            )

        db = get_client()
        rows = await db.query(
            table=spec.get("table", ""),
            select=spec.get("select", "*"),
            eq=spec.get("eq", {}),
            order=spec.get("order"),
            limit=int(spec.get("limit", 20)),
        )

        if not rows:
            return f"\U0001f5c4 No results for: <i>{html_mod.escape(query_text)}</i>"

        table_name = spec.get("table", "?")
        header = f"<b>\U0001f5c4 {html_mod.escape(table_name)}</b> — {len(rows)} rows\n"
        header += f"<i>Query: {html_mod.escape(query_text)}</i>\n\n"
        preview = json.dumps(rows[:10], indent=2, ensure_ascii=False, default=str)
        return header + "<pre>" + html_mod.escape(preview[:3000]) + "</pre>"

    except Exception as e:
        return f"\u274c DB query error: <code>{html_mod.escape(str(e)[:300])}</code>"


# =========================================================================== #
# /dbhealth
# =========================================================================== #

@router.message(Command("dbhealth"))
async def cmd_dbhealth(msg: Message) -> None:
    """Check Supabase project health and latency."""
    if not is_allowed(msg):
        return

    try:
        from tools.supabase_client import get_client, is_configured
        if not is_configured():
            await msg.answer(
                "\u26a0\ufe0f Supabase not configured. Set SUPABASE_URL + SUPABASE_ANON_KEY in .env",
                parse_mode="HTML",
            )
            return

        db = get_client()
        health = await db.health_check()
        url = os.getenv("SUPABASE_URL", "?")
        svc_set = bool(os.getenv("SUPABASE_SERVICE_ROLE_KEY"))

        if health["ok"]:
            icon = "\u2705"
            status = f"Online ({health['latency_ms']}ms)"
        else:
            icon = "\u274c"
            status = health.get("error") or f"HTTP {health.get('status_code')}"

        await msg.answer(
            f"{icon} <b>Supabase Health</b>\n"
            f"URL: <code>{html_mod.escape(url)}</code>\n"
            f"Status: <b>{status}</b>\n"
            f"Service Role Key: {'\u2705 set' if svc_set else '\u26a0\ufe0f not set (RLS bypass disabled)'}",
            parse_mode="HTML",
        )
    except Exception as e:
        await msg.answer(
            f"\u274c Health check failed: <code>{html_mod.escape(str(e)[:200])}</code>",
            parse_mode="HTML",
        )


# =========================================================================== #
# /dbtables
# =========================================================================== #

@router.message(Command("dbtables"))
async def cmd_dbtables(msg: Message) -> None:
    """List public tables in the Supabase project."""
    if not is_allowed(msg):
        return

    try:
        from tools.supabase_client import get_client, is_configured
        if not is_configured():
            await msg.answer("\u26a0\ufe0f Supabase not configured.", parse_mode="HTML")
            return

        db = get_client()
        # Query information_schema via RPC or direct REST
        rows = await db.query(
            "information_schema.tables",
            select="table_name,table_type",
            eq={"table_schema": "public"},
            order="table_name.asc",
            limit=100,
        )
        if not rows:
            await msg.answer("No public tables found.", parse_mode="HTML")
            return

        lines = ["<b>\U0001f5c4 Supabase Tables (public schema)</b>\n"]
        for r in rows:
            t = r.get("table_name", "?")
            tt = r.get("table_type", "")
            icon = "\U0001f4c4" if tt == "BASE TABLE" else "\U0001f441"
            lines.append(f"  {icon} <code>{html_mod.escape(t)}</code>")

        await msg.answer("\n".join(lines), parse_mode="HTML")

    except Exception as e:
        await msg.answer(
            f"\u274c Could not list tables: <code>{html_mod.escape(str(e)[:200])}</code>",
            parse_mode="HTML",
        )


# =========================================================================== #
# Helpers
# =========================================================================== #

def _extract_code_block(text: str) -> str:
    """Extract content from first ```...``` block."""
    import re
    m = re.search(r"```(?:typescript|ts|javascript|js|python)?\n([\s\S]*?)```", text)
    if m:
        return m.group(1).strip()
    return ""
