"""Shared state, helpers, and core runner functions for all handler modules."""

from __future__ import annotations

import asyncio
import contextlib
import html as html_mod
import logging
import re
import time

from aiogram.types import (
    CallbackQuery,
    FSInputFile,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    KeyboardButton,
    Message,
    ReplyKeyboardMarkup,
)

from llm_client import agent_loop, chat, chunk_output, verify_api_keys

logger = logging.getLogger(__name__)

# Tracks the last time the user sent any message — used by the curiosity engine
_last_user_message_ts: float = 0.0


def _format_for_telegram_html(text: str) -> str:
    """Lightweight formatter to improve readability in Telegram HTML mode.

    Keeps existing HTML intact while normalizing common markdown patterns
    generated by LLM responses.
    """
    if not text:
        return text

    out = html_mod.unescape(text).replace("\r\n", "\n").replace("\r", "\n")

    # Remove noisy markdown fences / backticks that often look robotic in chat
    out = out.replace("```", "\n")
    out = re.sub(r"`([^`\n]{1,120})`", r"<code>\1</code>", out)

    # Normalize markdown headers to bold lines
    out = re.sub(r"(?m)^\s*#{1,3}\s+(.+?)\s*$", r"<b>\1</b>", out)

    # Normalize markdown bullets into Telegram-friendly bullet glyph
    out = re.sub(r"(?m)^\s*-\s+", "• ", out)
    out = re.sub(r"(?m)^\s*\*\s+", "• ", out)

    # Normalize horizontal separators
    out = re.sub(r"(?m)^\s*---+\s*$", "━━━━━━━━━━━━━━━━━━━━", out)

    # Normalize long blank-line runs
    out = re.sub(r"\n{3,}", "\n\n", out)

    # Fix occasional orphan closing/opening code tags from model output
    out = out.replace("</code>\n</code>", "</code>")
    out = out.replace("<code><code>", "<code>")

    return out.strip()


# ── Shared mutable state ──────────────────────────────────────────────────────
ALLOWED_USER_ID: int = 0  # set by main.py at startup
_bot = None  # aiogram Bot instance, set in main.py on_startup
_user_thread: dict[int, str] = {}
_last_screenshot: dict[int, str] = {}
_start_time: float = time.time()

# Scheduler (initialised in on_startup)
_scheduler = None

# swarms_bot enterprise layer (initialised in on_startup)
_chief_of_staff = None

# opencode bridge (initialised in on_startup)
_opencode_bridge = None
_cost_router = None
_budget_manager = None
_security_guard = None
_audit_logger = None
_evaluator = None
_session_manager = None
_cost_metrics = None


# ── Auth ──────────────────────────────────────────────────────────────────────
def is_allowed(msg: Message) -> bool:
    if msg.from_user is not None and msg.from_user.id == ALLOWED_USER_ID:
        try:
            from core.hooks import get_hook_system  # type: ignore[reportAttributeAccessIssue]
            hs = get_hook_system()  # type: ignore[reportAttributeAccessIssue]
            if hs:
                hs.emit("command_received", msg=msg)
        except Exception:
            pass
        return True
    return False


def allowed_cb(cb: CallbackQuery) -> bool:
    return cb.from_user is not None and cb.from_user.id == ALLOWED_USER_ID


# ── UI components ─────────────────────────────────────────────────────────────
def main_keyboard() -> ReplyKeyboardMarkup:
    return ReplyKeyboardMarkup(
        keyboard=[
            [
                KeyboardButton(text="🏠 Home"),
                KeyboardButton(text="📊 Visualize"),
                KeyboardButton(text="⚙️ Status"),
            ],
            [
                KeyboardButton(text="\U0001f5a5 Do task"),
                KeyboardButton(text="\U0001f4f8 Screenshot"),
                KeyboardButton(text="\u26a1 Shell"),
            ],
            [
                KeyboardButton(text="\U0001f41b Debug"),
                KeyboardButton(text="\U0001f4bb Code"),
                KeyboardButton(text="⚡ Shell"),
            ],
        ],
        resize_keyboard=True,
        input_field_placeholder="Ask anything, or tap a button\u2026",
    )


def result_keyboard(model_used: str) -> InlineKeyboardMarkup:
    parts = model_used.split("/")
    provider = parts[0].upper()
    if provider == "OLLAMA_CHAT":
        provider = "LOCAL\U0001f512"
    return InlineKeyboardMarkup(
        inline_keyboard=[
            [
                InlineKeyboardButton(text="\U0001f44d", callback_data="fb:good"),
                InlineKeyboardButton(text="\U0001f504", callback_data="fb:retry"),
                InlineKeyboardButton(text=f"\u2191{provider}", callback_data="fb:info"),
            ]
        ]
    )


def screenshot_keyboard() -> InlineKeyboardMarkup:
    return InlineKeyboardMarkup(
        inline_keyboard=[
            [
                InlineKeyboardButton(text="\U0001f50d Analyze screen", callback_data="screen:analyze"),
                InlineKeyboardButton(text="\U0001f5b1 Do task on screen", callback_data="screen:do"),
            ]
        ]
    )


# ── Helper: send chunked messages ─────────────────────────────────────────────
async def send_chunked(msg: Message, text: str, model_used: str = "") -> None:
    if not text:
        return
    text = _format_for_telegram_html(text)
    with contextlib.suppress(Exception):
        logger.info(
            "[BOT_RESPONSE][chat=%s][model=%s] %s",
            msg.chat.id if msg.chat else None,
            model_used or "unknown",
            (text[:1200] + ("…" if len(text) > 1200 else "")).replace("\n", "\\n"),
        )
    chunks = chunk_output(text, max_length=4000)
    for i, chunk in enumerate(chunks):
        is_last = i == len(chunks) - 1
        markup = result_keyboard(model_used) if (is_last and model_used) else None
        try:
            await msg.answer(chunk, parse_mode="HTML", reply_markup=markup)
        except Exception:
            try:
                safe = html_mod.escape(chunk)
                await msg.answer(safe, parse_mode="HTML", reply_markup=markup)
            except Exception:
                await msg.answer(chunk, reply_markup=markup)
        if not is_last:
            await asyncio.sleep(0.3)


# ── Helper: typing indicator ──────────────────────────────────────────────────
async def _keep_typing(msg: Message) -> None:
    """Send typing indicator every 4s until cancelled. Stops on persistent errors."""
    consecutive_errors = 0
    while True:
        try:
            if msg.bot is not None:
                await msg.bot.send_chat_action(msg.chat.id, "typing")
            consecutive_errors = 0
        except Exception as e:
            consecutive_errors += 1
            if consecutive_errors >= 3:
                logger.debug("keep_typing stopped after %d errors: %s", consecutive_errors, e)
                break
        await asyncio.sleep(4)


async def _cancel_task(task: asyncio.Task | None) -> None:
    if task is None:
        return
    task.cancel()
    try:
        await task
    except asyncio.CancelledError:
        pass
    except Exception as e:
        logger.debug("Task cancelled with error: %s", e)


# ── Helper: key status string ─────────────────────────────────────────────────
def _key_status() -> str:
    status = verify_api_keys()
    names = {
        "CEREBRAS_API_KEY": "Cerebras   \u26a1 1,500 tok/s",
        "GROQ_API_KEY": "Groq       \U0001f680 function calling",
        "GEMINI_API_KEY": "Gemini     \U0001f4da 1M context",
        "OPENROUTER_API_KEY": "OpenRouter  \U0001f500 free models",
        "ZAI_API_KEY": "ZAI/GLM-4  \U0001f9e0 debug+math",
        "HF_TOKEN": "HuggingFace \U0001f917",
    }
    lines = ["<b>\U0001f511 API Keys</b>\n"]
    for k, label in names.items():
        icon = "\u2705" if status.get(k) else "\u274c"
        lines.append(f"  {icon} {label}")
    cloud = ["CEREBRAS_API_KEY", "GROQ_API_KEY", "GEMINI_API_KEY", "OPENROUTER_API_KEY"]
    lines.append("")
    lines.append("cloud active \u2713" if any(status.get(k) for k in cloud) else "\u26a0\ufe0f <b>no cloud keys!</b>")
    return "\n".join(lines)


# ── Core: agentic loop handler ────────────────────────────────────────────────
async def _run_agent_loop(msg: Message, task: str) -> None:
    """Run the agentic computer-use loop with live progress updates."""
    if not msg.from_user:
        return

    from_user_id = msg.from_user.id
    thread_id = _user_thread.get(from_user_id)

    with contextlib.suppress(Exception):
        logger.info(
            "[USER_CHAT][mode=agent_loop][chat=%s][user=%s] %s",
            msg.chat.id,
            from_user_id,
            (task[:1200] + ("…" if len(task) > 1200 else "")).replace("\n", "\\n"),
        )

    status_msg = await msg.answer("\U0001f916 on it\u2026")
    step_count = 0

    async def on_progress(step_text: str) -> None:
        nonlocal step_count
        step_count += 1
        try:
            if step_text.startswith("\U0001f4ad"):
                logger.info(
                    "[BOT_THOUGHT][chat=%s][user=%s] %s",
                    msg.chat.id,
                    from_user_id,
                    (step_text[:1200] + ("…" if len(step_text) > 1200 else "")).replace("\n", "\\n"),
                )
            else:
                logger.info(
                    "[BOT_PROGRESS][chat=%s][user=%s][step=%s] %s",
                    msg.chat.id,
                    from_user_id,
                    step_count,
                    (step_text[:1200] + ("…" if len(step_text) > 1200 else "")).replace("\n", "\\n"),
                )
        except Exception:
            pass
        try:
            if step_text.startswith("\U0001f4ad"):
                await msg.answer(
                    f"<i>{html_mod.escape(step_text)}</i>",
                    parse_mode="HTML",
                )
            else:
                await status_msg.edit_text(
                    f"<code>[{step_count}]</code> {html_mod.escape(step_text)}",
                    parse_mode="HTML",
                )
        except Exception:
            pass

    async def on_photo(path: str) -> None:
        try:
            photo_file = FSInputFile(path)
            await msg.answer_photo(
                photo=photo_file,
                caption="\U0001f4f8 current screen",
                reply_markup=screenshot_keyboard(),
            )
            _last_screenshot[from_user_id] = path
        except Exception as e:
            import logging

            logging.getLogger(__name__).error("Failed to send screenshot photo: %s", e)

    typing_task = asyncio.create_task(_keep_typing(msg))

    try:
        response, model_used = await agent_loop(
            task,
            progress_fn=on_progress,
            photo_cb=on_photo,
            thread_id=thread_id,
            user_id=str(msg.from_user.id) if msg.from_user else None,
        )
        await _cancel_task(typing_task)
        with contextlib.suppress(Exception):
            await status_msg.delete()
        await send_chunked(msg, response, model_used=model_used)

    except Exception as e:
        await _cancel_task(typing_task)
        from core.error_humanizer import humanize_error_for_display

        friendly = humanize_error_for_display(e, context="/do agent loop")
        err_short = str(e)[:300]
        hint = friendly
        try:
            await status_msg.edit_text(
                f"{hint}\n\n<code>{err_short}</code>",
                parse_mode="HTML",
            )
        except Exception:
            await msg.answer(
                f"{hint}\n\n<code>{err_short}</code>",
                parse_mode="HTML",
            )


# ── Core: single-turn chat handler ────────────────────────────────────────────
async def _execute_chat(
    msg: Message,
    task: str,
    forced_agent: str | None = None,
    show_thinking: bool = True,
    routing_hint: str | None = None,
) -> None:
    """Single-turn LLM chat with typing indicator and chunked output."""
    # FIX #5: Guard against msg.from_user being None
    if not msg.from_user:
        return

    selected_agent = forced_agent or "general"

    with contextlib.suppress(Exception):
        logger.info(
            "[USER_CHAT][mode=chat][chat=%s][user=%s][agent=%s] %s",
            msg.chat.id,
            msg.from_user.id,
            selected_agent,
            (task[:1200] + ("…" if len(task) > 1200 else "")).replace("\n", "\\n"),
        )

    # Use chat.id as thread_id so conversation history is tracked per-chat
    thread_id = str(msg.chat.id) if msg.chat else str(msg.from_user.id)

    typing_task = asyncio.create_task(_keep_typing(msg))
    try:
        response, model_used = await chat(
            task,
            agent_key=selected_agent,
            show_thinking=show_thinking,
            user_id=str(msg.from_user.id),
            thread_id=thread_id,
            routing_hint=routing_hint,
        )
        await _cancel_task(typing_task)
        await send_chunked(msg, response, model_used=model_used)
    except Exception as e:
        await _cancel_task(typing_task)
        from core.error_humanizer import humanize_error_for_display

        friendly = humanize_error_for_display(e, context="chat")
        err_short = str(e)[:300]
        hint = friendly
        await msg.answer(
            f"{hint}: <code>{err_short}</code>",
            parse_mode="HTML",
        )
