"""
Context Maximizer for Elite OpenCode Stack
Token budget tracking + heuristic compression.
Ollama integration: phi model via Ollama when available, else MiniMax API, else heuristic.
"""
import json
import os
import re
import time
from pathlib import Path
from typing import Optional


# ── Token counter (tiktoken-style approximation) ──────────────────
def count_tokens(text: str) -> int:
    """Approximate token count. Accurate within ~5% for English+code mix."""
    return max(1, len(text) // 4)

# ── Heuristic pruning (no model needed) ───────────────────────────
def prune_text(text: str) -> tuple[str, int]:
    """
    Remove obvious waste: duplicates, boilerplate, verbose sections.
    Returns (pruned_text, chars_removed).
    """
    original_len = len(text)
    lines = text.split('\n')
    pruned = []
    seen_lines = set()

    for line in lines:
        stripped = line.strip()
        # Skip exact duplicate lines (keep first occurrence)
        if stripped in seen_lines and len(stripped) > 20:
            continue
        seen_lines.add(stripped)
        # Skip obvious boilerplate license headers
        if re.match(r'^\s*\*+\s*Copyright\s+\d{4}', stripped):
            continue
        if re.match(r'^\s*SPDX-License-Identifier:', stripped):
            continue
        # Skip auto-generated markers
        if re.search(r'Generated by|autogenerated|auto-generated', stripped, re.I):
            continue
        pruned.append(line)

    result = '\n'.join(pruned)
    return result, original_len - len(result)

# ── Context budget tracker ────────────────────────────────────────
class ContextBudget:
    TOTAL = 204800
    SYSTEM_RESERVED = 6000
    OUTPUT_RESERVED = 8192
    SAFETY_BUFFER = 2048
    AVAILABLE = TOTAL - SYSTEM_RESERVED - OUTPUT_RESERVED - SAFETY_BUFFER

    def __init__(self):
        self.used = 0
        self.log = []
        self.pruned_chars = 0

    def add(self, label: str, content: str, compress_ratio: float | None = None):
        pruned_content, chars_removed = prune_text(content)
        self.pruned_chars += chars_removed

        if compress_ratio and compress_ratio < 1.0 and len(pruned_content) > 5000:
            keep_start = int(len(pruned_content) * 0.4)
            keep_end = int(len(pruned_content) * 0.4)
            target = int(len(pruned_content) * compress_ratio)
            if keep_start + keep_end < target:
                pruned_content = (pruned_content[:keep_start] +
                                  f'\n\n[... compressed {int((1-compress_ratio)*100)}% ...]\n\n' +
                                  pruned_content[-keep_end:])
            tokens = count_tokens(pruned_content)
            self.log.append(f"{label}: {count_tokens(content)}→{tokens} tokens (pruned {chars_removed} chars)")
        else:
            tokens = count_tokens(pruned_content)
            self.log.append(f"{label}: {tokens} tokens (pruned {chars_removed} chars)")

        self.used += tokens
        return pruned_content

    def remaining(self) -> int:
        return self.AVAILABLE - self.used

    def usage_pct(self) -> float:
        return round(self.used / self.AVAILABLE * 100, 1)

    def report(self) -> str:
        lines = ["── Context Budget ──"]
        lines += self.log
        lines += [f"Total used: {self.used:,} / {self.AVAILABLE:,} ({self.usage_pct()}%)"]
        lines += [f"Remaining:  {self.remaining():,} tokens"]
        lines += [f"Chars pruned: {self.pruned_chars:,}"]
        return "\n".join(lines)

# ── opencode.json patcher ─────────────────────────────────────────
def patch_opencode_config(config_path: str = "/home/newadmin/swarm-bot/.opencode/opencode.json"):
    path = Path(config_path)
    config = json.loads(path.read_text()) if path.exists() else {}

    config["compaction"] = {
        "reserved": 8192,
        "threshold": 0.98,
        "maxContext": 204800,
    }

    path.write_text(json.dumps(config, indent=2))
    print(f"✅ Patched {config_path}")
    print("   compaction.threshold: 0.98")
    print("   compaction.reserved: 8,192")
    print("   compaction.maxContext: 204,800")

# ── Backend detection for compression ───────────────────────────
_compressor = None
_compressor_backend = None

def get_compressor_backend():
    """Detect available compression backend. Priority: Ollama phi > MiniMax API > None."""
    global _compressor, _compressor_backend

    if _compressor_backend is not None:
        return _compressor_backend

    # Check Ollama for phi model
    try:
        import requests
        r = requests.get("http://localhost:11434/api/tags", timeout=3)
        models = [m["name"] for m in r.json().get("models", [])]
        phi = next((m for m in models if "phi" in m.lower()), None)
        if phi:
            _compressor_backend = f"ollama/{phi}"
            print(f"ℹ️ Compression backend: Ollama/{phi}")
            return _compressor_backend
    except Exception:
        pass

    # Check if MiniMax API key is available
    if os.environ.get("MINIMAX_API_KEY"):
        _compressor_backend = "minimax-api"
        print("ℹ️ Compression backend: MiniMax API")
        return _compressor_backend

    _compressor_backend = "heuristic"
    print("ℹ️ Compression backend: heuristic (no model available)")
    return _compressor_backend

# ── Main compression function ─────────────────────────────────────
def compress(text: str, ratio: float = 0.5, instruction: str = "",
             question: str = "") -> dict:
    """
    Compress text. Uses Ollama phi if available, else MiniMax API, else heuristic.
    ratio = fraction to KEEP (0.5 = keep 50%).
    """
    start = time.time()
    original_tokens = count_tokens(text)

    # Stage 1: prune obvious waste
    pruned, chars_removed = prune_text(text)

    # Stage 2: apply ratio-based compression
    backend = get_compressor_backend()

    if backend.startswith("ollama/"):
        # Ollama phi compression via LLMLingua
        try:
            import requests
            from llmlingua import PromptCompressor

            model_name = backend.replace("ollama/", "")
            compressor = PromptCompressor(
                model_name=f"ollama/{model_name}",
                use_llmlingua2=False,
                device_map="cpu",
                open_api_config={
                    "api_base": "http://localhost:11434/v1",
                    "api_key": "ollama",
                }
            )
            result = compressor.compress_prompt(
                context=[pruned],
                instruction=instruction,
                question=question,
                ratio=(1.0 - ratio),
                rank_method="longllmlingua",
            )
            compressed = result["compressed_prompt"]
            comp_tokens = count_tokens(compressed)
            return {
                "compressed": compressed,
                "original_tokens": original_tokens,
                "compressed_tokens": comp_tokens,
                "savings_pct": round((1 - comp_tokens / max(original_tokens, 1)) * 100, 1),
                "elapsed_ms": round((time.time() - start) * 1000),
                "backend": backend,
            }
        except Exception as e:
            print(f"⚠️ Ollama compression failed: {e}. Trying MiniMax API.")

    if backend in ("minimax-api",) and os.environ.get("MINIMAX_API_KEY"):
        # MiniMax API compression
        try:
            import litellm
            keep_pct = int(ratio * 100)
            compress_prompt = f"""You are a context compressor. Compress to ~{keep_pct}% of length.
RULES:
- Keep all technical facts, code logic, variable names, function signatures
- Remove: filler words, redundant explanations, repeated info, verbose phrasing
- Output ONLY compressed text, no preamble
- Preserve code blocks exactly

{"TASK CONTEXT: " + question if question else ""}

TEXT TO COMPRESS:
{pruned}"""

            response = litellm.completion(
                model="minimax/MiniMax-M2.7",
                api_base="https://api.minimax.chat/v1",
                api_key=os.environ["MINIMAX_API_KEY"],
                messages=[{"role": "user", "content": compress_prompt}],
                max_tokens=max(500, int(original_tokens * ratio)),
                temperature=0.1,
            )
            compressed = response.choices[0].message.content
            comp_tokens = count_tokens(compressed)
            return {
                "compressed": compressed,
                "original_tokens": original_tokens,
                "compressed_tokens": comp_tokens,
                "savings_pct": round((1 - comp_tokens / max(original_tokens, 1)) * 100, 1),
                "elapsed_ms": round((time.time() - start) * 1000),
                "backend": "minimax-api",
            }
        except Exception as e:
            print(f"⚠️ MiniMax API compression failed: {e}. Using heuristic.")

    # Heuristic fallback: keep beginning + end
    words = pruned.split()
    keep_count = int(len(words) * ratio)
    compressed = " ".join(words[:keep_count])
    comp_tokens = count_tokens(compressed)
    return {
        "compressed": compressed,
        "original_tokens": original_tokens,
        "compressed_tokens": comp_tokens,
        "savings_pct": round((1 - comp_tokens / max(original_tokens, 1)) * 100, 1),
        "elapsed_ms": round((time.time() - start) * 1000),
        "backend": "heuristic",
    }

if __name__ == "__main__":
    import sys
    if "--patch-config" in sys.argv:
        patch_opencode_config()
    elif "--test" in sys.argv:
        budget = ContextBudget()
        sample = "def calculate_tax(salary, ptkp, category):\n    pass\n" * 200
        budget.add("test_code", sample, compress_ratio=0.5)
        print(budget.report())
        backend = get_compressor_backend()
        print(f"Compression backend: {backend}")
    elif "--compress" in sys.argv:
        text = sys.stdin.read() if not sys.stdin.isatty() else "sample text"
        result = compress(text, ratio=0.5, question="test")
        print(f"Original: {result['original_tokens']} tokens")
        print(f"Compressed: {result['compressed_tokens']} tokens")
        print(f"Savings: {result['savings_pct']}%")
        print(f"Backend: {result['backend']}")
    else:
        print("Usage: python3 context_maximizer.py [--patch-config | --test | --compress]")