use_default_settings: true

general:
  instance_name: "SearXNG (local)"
  debug: false
  enable_metrics: false

server:
  secret_key: "6e89ce6e2450286c7e584d431b974e10e1343c5d8b636eb3c4dca2ea76d16963"
  bind_address: "127.0.0.1"
  port: 8888
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

ui:
  static_use_hash: true
  default_locale: ""
  default_theme: simple

outgoing:
  request_timeout: 5.0
  max_request_timeout: 10.0

valkey:
  url: false
